from ase.build import bulk


def get_atoms():
    """ Atomic structures generated.

    Returns:
        atoms (ase.Atoms)
    """
    # Code Generated by Taiga CD Portal
    atoms = bulk('Si', 'diamond', a=5.43)
    
    return atoms
